config/routes.rb
Rails.application.routes.draw do
  get 'daily_balances/show'
  # static_pages
  get "/home",  to: "static_pages#home"
  get "/help",  to: "static_pages#help"
  get "/about", to: "static_pages#about"
  root "static_pages#home"

  # users
  get "/signup", to: "users#new"
  post "/signup", to: "users#create"
  resources :users, only: %i[new create edit update] do
    resources :daily_balances, only: :show, param: :record_date
    resource :images, only: %i[edit update], module: :users
    resource :image_initializations, only: :update, module: :users
    resource :self_categories, only: %i[new create], module: :users
  end

  # book_records
  resources :book_records, only: %i[create destroy]

  # sessions
  get "/login", to: "sessions#new"
  post "/login", to: "sessions#create"
  delete "/logout", to: "sessions#destroy"

  # 試用ユーザーへログインする
  get "/sample_login", to: "sessions#sample_login"
end

app/models/user.rb
class User < ApplicationRecord
  attr_accessor :remember_token
  has_many :book_records, dependent: :destroy
  has_many :daily_balances, dependent: :destroy
  before_save { email.downcase! }
  mount_uploader :img, ImgUploader
  mount_uploader :header_image, HeaderImageUploader
  validates(:name, presence: true, length: { maximum: 20 })
  REGEX_FOR_VALID_EMAIL = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i
  validates(:email, presence: true,
                    length: { maximum: 128 },
                    uniqueness: { case_sensitive: false },
                    format: { with: REGEX_FOR_VALID_EMAIL })
  validates(:password, presence: true, length: { minimum: 8 }, allow_nil: true)
  has_secure_password

  def self.digest(string)
    cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST : BCrypt::Engine.cost
    BCrypt::Password.create(string, cost: cost)
  end

  def self.new_token
    SecureRandom.urlsafe_base64
  end

  def set_remember_digest
    self.remember_token = User.new_token
    update_attribute(:remember_digest, User.digest(remember_token))
  end

  def authenticated?(remember_token)
    return false if remember_digest.nil?

    BCrypt::Password.new(remember_digest).is_password?(remember_token)
  end

  def login_cookie_forget
    update_attribute(:remember_digest, nil)
  end

  def sum_of_amount_for_expenditure
    sum_expenditure = 0
    book_records.each do |record|
      sum_expenditure += record.amount if record.direction == zero
    end
  end

  def sum_of_amount_for_income
    sum_income = 0
    book_records.each do |record|
      sum_income += record.amount if record.direction == 1
    end
  end
end

app/controllers/users/image_initializations_controller.rb
class Users::ImageInitializationsController < ApplicationController
  before_action :find_user, only: :update
  before_action :logged_in_user, only: :update
  before_action :correct_user_for_child_controller, only: :update

  def update
    @user.img = "default_img.png"
    @user.header_image = "default_header_image.png"
    if @user.save
      flash[:success] = "画像を初期画像へ戻しました。"
      redirect_to(edit_user_images_path(@user))
    else
      flash.now[:danger] = "エラーが発生しました。時間をおいてもう一度実行してみてください。"
      render("users/images#edit")
    end
  end
end

app/controllers/users/images_controller.rb
class Users::ImagesController < ApplicationController
  before_action :find_user, only: %i[edit update]
  before_action :logged_in_user, only: %i[edit update]
  before_action :correct_user_for_child_controller, only: %i[edit update]

  def edit
    @settings_class = ""
    @images_class = "active"
    @category_class = ""
  end

  def update
    if @user.update_attributes(user_images_params)
      flash[:success] = "画像を更新しました。"
      redirect_to(edit_user_images_path(@user))
    else
      flash.now[:danger] = "エラーが発生しました。時間をおいてもう一度実行してみてください。"
      render("users/images#edit")
    end
  end
end

app/controllers/users/self_categories_controller.rb
class Users::SelfCategoriesController < ApplicationController
  before_action :find_user, only: %i[new create]
  before_action :logged_in_user, only: %i[new create]
  before_action :correct_user_for_child_controller, only: %i[new create]

  def new
    @category = Category.new
    @settings_class = ""
    @images_class = ""
    @category_class = "active"
  end

  def create
    @category = Category.new(category_params)
    if @category.save
      flash[:success] = "新しい収支カテゴリを登録しました。"
      redirect_to(new_user_self_categories_url)
    else
      flash.now[:danger] = "エラーが発生しました。時間をおいてもう一度実行してみてください。"
      render("users/self_categories#new")
    end
  end

  private

  def category_params
    params.require(:category).permit(:name, :color, :user_id)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :logged_in_user, only: %i[edit update]
  before_action :correct_user, only: %i[edit update]

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    @user.img = "default_img.png"
    @user.header_image = "default_header_image.png"
    if @user.save
      log_in(@user)
      flash[:success] = "ようこそ！ #{@user.name}さん！"
      redirect_to(root_url)
    else
      render("new")
    end
  end

  def edit
    @user = User.find_by(id: params[:id])
    @settings_class = "active"
    @images_class = ""
    @category_class = ""
  end

  def update
    @user = User.find_by(id: params[:id])
    if @user.update_attributes(user_params)
      flash[:success] = "基本情報を更新しました。"
      redirect_to(edit_user_path(@user))
    else
      render("settings_edit")
    end
  end

  private

  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end

  def correct_user
    @user = User.find(params[:id])
    redirect_to(root_url) unless current_user?(@user)
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/images/edit.html.erb
<% provide(:title, "プロフィール画像の変更") %>
<div class="settings-title">
  プロフィール画像の変更
</div>
<div class="row">
  <%= render("shared/setting_sidebar", settings: @settings_class, images: @images_class, category: @category_class) %>
  <div class="col-md-6 image-settings-form">
    <%= form_for(@user, url: user_images_path(@user), html: {id:"edit_user_image"}) do |f| %>
      <%= render("shared/error_messages") %>

      <%= f.label :header_image, "ヘッダー画像"%>
      <%= f.file_field :header_image, accept: "image/jpeg, image/gif, image/png", class: "form-control" %>

      <%= f.label :email, "プロフィール画像" %>
      <%= f.file_field :img, accept: "image/jpeg, image/gif, image/png", class: "form-control" %>

      <input type="button" value="設定の変更" name="commit" class="btn image-settings-update-button" data-disable-with="設定の変更" onClick="checkNilImages()" >
    <% end %>
    <%= link_to "初期画像に戻す", user_image_initializations_path(@user),
                                class: "btn image-reset-button",
                                method: :patch,
                                data: {confirm: "画像を初期状態に戻しますか？"} %>
  </div>
</div>

<script>
function checkNilImages()
{
  const header_image_file = $("input[id='user_header_image']")[0].value;
  const   icon_image_file = $("input[id='user_img']")[0].value;
  if( header_image_file === "" && icon_image_file === "" )
  {
    alert("いずれの画像ファイルも選択されていません。");
    return;
  }

  if( window.confirm("選択した画像ファイルをアップロードしますか？") ) $("#edit_user_image").submit();
}
</script>